
test_task:
  container:
    dockerfile: Dockerfile
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements.txt
    populate_script: pip install -r requirements.txt
  test_script: python -m pytest --color=yes tests -s
